export const INIT_NEWS_ITEMS = "INIT_NEWS_ITEMS",
    INIT_NEWS_ITEMS_SUCCESS = "INIT_NEWS_ITEMS_SUCCESS",
    INIT_NEWS_ITEMS_FAILURES = "INIT_NEWS_ITEMS_FAILURES",
    CLOSE_MODAL = "CLOSE_MODAL",
    OPEN_MODAL = "OPEN_MODAL";